Update training

diff --git a/training b/training
--- a/training
+++ b/training
@@ -37,4 +37,16 @@ function ChooseDataBase {
     mainMenu
   fi
 }
+function createDB {
+echo -e "Enter Database Name: \c"
+read DataBaseName
+mkdir ./DBMS/$DataBaseName
+if [[ $? == 0 ]]
+then
+echo "Database Created Successfully"
+else
+echo "Error Creating Database $DataBaseName"
+fi
+mainMenu
+}
 
