Update training

diff --git a/training b/training
--- a/training
+++ b/training
@@ -49,4 +49,29 @@ echo "Error Creating Database $DataBaseName"
 fi
 mainMenu
 }
+function ChangeDBName {
+  echo -e "Enter Current Database Name: \c"
+  read DataBaseName
+  echo -e "Enter New Database Name: \c"
+  read newName
+  mv ./DBMS/$DataBaseName ./DBMS/$newName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Renamed Successfully"
+  else
+    echo "Error Renaming Database"
+  fi
+  mainMenu
+}function dropDB {
+  echo -e "Enter Database Name: \c"
+  read DataBaseName
+  rm -r ./DBMS/$DataBaseName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Dropped Successfully"
+  else
+    echo "Database Not found"
+  fi
+  mainMenu
+}
+
+
 
