Update training

diff --git a/training b/training
--- a/training
+++ b/training
@@ -166,6 +166,49 @@ function createTable {
   fi
 }
 
-function dropTable{}
+function dropTable{
+  echo -e "Enter Table Name: \c"
+  read tName
+  rm $tName .$tName 2>>./.error.log
+  if [[ $? == 0 ]]
+  then
+    echo "Table Dropped Successfully"
+  else
+    echo "Error Dropping Table $tName"
+  fi
+  tablesMenu
+}
 function insert{}
-function updateTable{
+function updateTable{}
+function deleteFromTable{}
+
+function selectMenu {
+  echo -e "\n\n+---------------Select Menu--------------------+"
+  echo "| 1. Select All Columns of a Table              |"
+  echo "| 2. Select Specific Column from a Table        |"
+  echo "| 3. Select From Table under condition          |"
+  echo "| 4. Aggregate Function for a Specific Column   |"
+  echo "| 5. Back To Tables Menu                        |"
+  echo "| 6. Back To Main Menu                          |"
+  echo "| 7. Exit                                       |"
+  echo "+----------------------------------------------+"
+  echo -e "Enter Choice: \c"
+  read ch
+  case $ch in
+    1) selectAll ;;
+    2) selectCol ;;
+    3) clear; selectCon ;;
+    4) ;;
+    5) clear; tablesMenu ;;
+    6) clear; cd ../.. 2>>./.error.log; mainMenu ;;
+    7) exit ;;
+    *) echo " Wrong Choice " ; selectMenu;
+  esac
+}
+
+
+
+
+
+
+
